### PR TITLE
Update lightstep logo

### PR DESCRIPTION
**Pull request by enceeobee**
Replaces the old logo with the new one.

Screen Shot 2020-10-07 at 11 12 10 AM

### CODE REVIEW

**Review by ishg — CHANGES_REQUESTED** [review]
While we are updating logo, can we also update the rest of the branding? (mostly the camelcase to normal case where applicable) Thanks!

**Comment by enceeobee** [comment]
> While we are updating logo, can we also update the rest of the branding? (mostly the camelcase to normal case where applicable) Thanks!

I hear you @ishg, and created this PR with strictly logo changes to avoid accidental side effects of changing the name somewhere I shouldn't. For example, if we rename the app to "Lightstep App", Grafana may interpret it as a new, discrete plugin rather than the next version of the "LightStep App".

Also, I thought updating the logo was arguably the more important fix and a worthy iteration.

That said, I'll look again for innocuous company name changes (e.g. in READMEs or descriptions).

**Review by dcarrot2 — APPROVED** [review]

**Comment by ishg** [comment]
@enceeobee I think since we don't have the plugin released in the Grafana repo, Grafana is not really going to know about the name change either way right? Since users install it directly from our repo this should be okay. Once we are in the Plugins directory on Grafana then I think we might encounter the situation as you mention above.

**Comment by enceeobee** [comment]
@ishg , I was mostly thinking about goofs like the screenshot below happening within the local Grafana instance. I just don't know what to expect, which is why I decided to leave the name alone. Maybe an extra datasource popping up isn't actually a big deal?

Screen Shot 2020-10-14 at 11 02 52 AM

**Comment by ishg** [comment]
Ah, I see what you mean. Yeah, I think this is just grafana aliasing the existing plugin name as default, when setting up a data source you can actually define your own name. the -1 still happens if you just add the same data source twice. This is something we can mention in the release as a "breaking change" so anyone upgrading can be aware. 
image

**Review by cdsackes — APPROVED** [review]
i'm planning on a follow up change to get us on the grafana page- so i could go in and change the names there if it doesn't make it in this pr. just lmk

**Pull request merged**
