### PR TITLE
CORS disable for Grafana with direct access

### PR DESCRIPTION
**Pull request by miry**
In Grafana 7.0.3 the plugin does not show the datapoints.
Instead there is a error message in the logs:

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.lightstep.com/public/v0.2/Org/projects/Project/streams. (Reason: header ‘content-type’ is not allowed according to header ‘Access-Control-Allow-Headers’ from CORS preflight response).

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.lightstep.com/public/v0.2/org/projects/Project/streams. (Reason: CORS request did not succeed).

Uncaught (in promise) TypeError: NetworkError when attempting to fetch resource.
```

The networking tabs shows: 

`OPTIONS | https://api.lightstep.com/public/v0.2/Zalando/projects/Production/streams` with status `CORS missing Allow Header`

It means the header Content Type is not allowed in the requests to API.

Thanks to @pitr and @vetinari for help and contribution.

//cc @lfroment0

### CODE REVIEW

**Comment by miry** [comment]
@joeblubaugh can you check the changes in this PR?

**Comment by joeblubaugh** [comment]
After answering please click "re-request review" in the sidebar. That's a more reliable notifier for me about review work I need to do.

Thank you again for the contribution!

**Comment by miry** [comment]
> Do requests pass through a proxy, and if so, what proxy?

@joeblubaugh we use direct method of communication. It means the requests created directly from browsers to the API lightstep server, as you see in the example.
The logs came from the browser directly to API server of lightstep.

**Comment by miry** [comment]
> I think this is an OK workaround for now - Lightstep doesn't enforce the application/json header on our side right now, but I would like to use it in case we want to support additional content types in the future.

It is true. I admit this hack is very bad.

**Comment by ishg** [comment]
Hi @miry, if you switch to the proxy method instead of the direct communication method, that seems to work fine. I just tested with Grafana 7.1.1 and Grafana 7.0.3 and the proxy method works without any errors. It uses the Grafana servers to proxy the request as the OPTIONS request would otherwise fail on browser side. 

Are there any blockers from your side  using this method? 

image

**Comment by pitr** [comment]
direct method is preferred, as the latency would be lower

**Comment by joeblubaugh** [comment]
@miry @pitr I did some more investigation here, and I believe this is actually a bug in our public API CORS preflighting. We should be more generous with out `Access-Control-Allow-Headers` response. I will update our `Content-Type` filter. I'll ping this PR when it is deployed, and you can revert this change in your local codebase.

**Comment by joeblubaugh** [comment]
The fix for this issue on our side has shipped. Can you test it out with the content type header added back in?

**Pull request closed without merging**
