### PR TITLE
Introduce Operation and errros per second options

### PR DESCRIPTION
**Pull request by miry**
There is a good practice to use Requests per second for dashboards.
With a current limitations of the API, it is possible specify min resolution as `1m`. That would gives max Requests/operations per minute. In same time, of the resolution small like 1m, then API would not allow you to get a bigger range like weeks or months. It makes using panel with a static range predefined, that makes discomfort of using charts when change the ranges.

Also Lightstep UI gives ability to check Rate (Request per second):

image

## Proposal

Allow to show datapoints with calculations to check operation per second for Operations and Errors as separate series.

UI changes looks like:

image

### CODE REVIEW

**Comment by joeblubaugh** [comment]
@miry we won't be supporting a resolution than one minute in the near future. On ranges like days or weeks you can ask for wider resolutions. What's your concern there? I don't think I understand the question well.

**Comment by miry** [comment]
@joeblubaugh Sure. The standard way to show throughput is Request per second. The solution provides a converstion from  dynamyc resolution(from 60 seconds till max allowed by API) to Reqeusts per second. 
For example: I can specify Resolution field 3600 seconds and I got 1 data point per hour, the chart should show the value divided by 3600.

**Comment by zeitlinger** [comment]
Superceded by https://github.com/lightstep/lightstep-grafana-plugin/pull/95

**Comment by smithclay** [comment]
Merged and released in `v1.2.0`

**Pull request closed without merging**
